"""
Z-SENTINEL AI — Pydantic Data Models & Schemas
IBM Z Datathon 2026
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class Transaction(BaseModel):
    """Represents a financial or operational transaction originating from IBM Z."""
    transactionId: str = Field(..., example="TX-83921")
    userId: str = Field(..., example="USR-7741")
    amount: float = Field(..., example=94500.00)
    timestamp: str = Field(..., example="2026-09-27T09:42:00Z")
    location: str = Field(..., example="Zurich, CHE")
    ipAddress: str = Field(..., example="194.209.12.8")
    deviceId: str = Field(..., example="DEV-99")
    transactionType: str = Field(default="WIRE_TRANSFER", example="WIRE_TRANSFER")
    accountType: str = Field(default="COMMERCIAL_CHECKING", example="COMMERCIAL_CHECKING")
    previousTransactionCount: int = Field(default=0, example=5)
    deviceKnown: bool = Field(default=False, example=False)
    locationKnown: bool = Field(default=False, example=False)
    memo: Optional[str] = Field(default=None, example="Invoice payment with PAN 4929-1102-9481-3210")


class SecurityAnalysisResult(BaseModel):
    """Output generated by the layered Rule + ML security engine."""
    transactionId: str
    anomalyScore: float = Field(..., description="Raw scikit-learn Isolation Forest score")
    riskScore: int = Field(..., ge=0, le=100, description="Composite score between 0 and 100")
    riskLevel: str = Field(..., example="CRITICAL")  # LOW, MEDIUM, HIGH, CRITICAL
    reasons: List[str] = Field(default_factory=list)
    action: str = Field(..., example="BLOCK")  # ALLOW, CHALLENGE, BLOCK
    aiProvider: str = Field(default="Local Security Engine", example="Local Security Engine")
    explanation: Optional[str] = None


class PrivacyDetectionResult(BaseModel):
    """Identified PII entity and corresponding deterministic redaction."""
    piiType: str = Field(..., example="PRIMARY_ACCOUNT_NUMBER")
    severity: str = Field(..., example="HIGH")
    originalPattern: str
    maskedValue: str = Field(..., example="************3210")
    action: str = Field(default="MASKED", example="MASKED")
    timestamp: str


class ThreatEvent(BaseModel):
    """Threat incident card for SOC triage."""
    threatId: str = Field(..., example="THR-1082")
    threatType: str = Field(..., example="Potential Account Takeover")
    severity: str = Field(..., example="CRITICAL")  # LOW, MEDIUM, HIGH, CRITICAL
    riskScore: int = Field(..., ge=0, le=100)
    affectedTransaction: str
    reasons: List[str]
    recommendedAction: str
    timestamp: str
    status: str = Field(default="NEW", example="NEW")  # NEW, INVESTIGATING, RESOLVED


class CopilotQueryRequest(BaseModel):
    """Query submitted to the AI Security Copilot console."""
    query: str
    transactionId: Optional[str] = None
    allowCloudFallback: bool = Field(default=True)


class CopilotQueryResponse(BaseModel):
    """Copilot response with transparent provenance tagging."""
    response: str
    provider: str = Field(..., example="Local Security Engine")  # "Local Security Engine" or "Groq AI"
    reasoningSteps: List[str] = Field(default_factory=list)
    executionTimeMs: float = 0.0


class IBMZTelemetryStatus(BaseModel):
    """Health and status of IBM Z mainframe adapter."""
    connectionStatus: str
    streamMode: str  # "simulated" or "live"
    pipelineStatus: str
    eventsProcessed: int
    threatsDetected: int
    lastEventTimestamp: str
    adapterHealth: str
